Order_Management_System_using_Django_Framework/Order-management-system/customers/urls.py
from django.urls import path

from customers import views
from customers import pdfviews,billviews
from customers import exportviews



app_name='customer_app'

urlpatterns=[
    path('create/',views.create,name='create'),
    # path('',views.CustomerPagination.as_view(),name="customer_pagination"),#it assists to show page
    path('list/',views.index,name='list'),#assists to show data
    path('edit/',views.edit,name='edit'),#here i pass primary key
    path('search/',views.search,name="search"),
    path('delete/',views.delete,name="delete"),
    path('customer-id-<int:cid>/order/',views.cus_ord_view,name="view"),
    path('pdf/',pdfviews.GeneratePDF.as_view(),name="pdf"),
    path('orders/bill/<int:cid>',billviews.GenerateBILL.as_view(),name="bill"),
    path('export/',exportviews.export,name="export"),
    
]

Order_Management_System_using_Django_Framework/Order-management-system/orders/urls.py
from django.urls import path
from orders import views,pdfviews

app_name = "order_app"

urlpatterns = [
    path('create/<int:cid>/', views.create, name = "create"),#I pass cid as for instance to show customer name when i click Add Order
    path('list/',views.index,name="list"),
    path('pdf/',pdfviews.GeneratePDF.as_view(),name="pdf"),
    path('edit/customer-id-<int:cid>/order-id-<int:oid>/',views.edit,name="edit"),
    path('search/',views.search,name="search"),
    path('delete/<int:oid>/',views.delete,name="delete"),
    
]

Order_Management_System_using_Django_Framework/Order-management-system/registers/urls.py
from django.urls import path

from registers import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetDoneView

app_name ='register_app'

urlpatterns = [
    path('login/',views.loginPage,name="login"),
    path('register/',views.SignupView,name="register"),
    path('logout/',views.UserLogout.as_view(),name="logout"),
    path('profile/',views.UserProfile,name="user_view"),

    # path('dash/<int:cid>/',views.dashboard_data,name = "dash-price-data")
  
    # path('logout/',a)
   
     ]





'''
for which email is sent use SMTP configuration in settings.py
https://docs.djangoproject.com/en/3.0/topics/auth/default/
Submit email form    -->PasswordResetViews.as_views()
email sent success  -->PasswordResetDoneView.as_views()
Link to password reser form in email ---user see email   -->PasswordResetConfirmView.as_views()
password sucessfully changed message and user can login using new password   -->PasswordResetCompleteView.as_views()


-------------------------------------------------------------
-->python decouple concept for email and other things secrete|
--------------------------------------------------------------
'''

Order_Management_System_using_Django_Framework/Order-management-system/rms/urls.py
from django.contrib import admin
from django.urls import path,include
# from registers.views  import dashboard

from registers import views

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView




urlpatterns = [
	path('admin/', admin.site.urls),
	path('',views.first_page,name="home"),
	path('dashboard/',views.dashboard,name="dashboard"),

#    path('',include('django.contrib.auth.urls')),
	
	path('user/',include('registers.urls', namespace = 'register_app')),
	path('customers/',include('customers.urls', namespace="customer_app")),
	path('products/',include('products.urls', namespace="product_app")),#namespace is the app_name in products.urls
	path('orders/',include('orders.urls', namespace="order_app")),
 
	
	
#    path('',include('registers.profile_urls',namespace="view_app")),

	path('reset_password/',auth_views.PasswordResetView.as_view(template_name = 'passwordreset/password_reset_email.html'), 
		 name = "password_reset"),
	
	path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name = 'passwordreset/password_reset_sent.html'), 
		 name = "password_reset_done"),
	
	path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='passwordreset/password_reset_form.html'),
		 name="password_reset_confirm"),  
	   
	 #<token> check  for valid user or not--><uidb64> user id encoded in base 64--this email is sent to the user
	 #<uidb64> helps to know user who request for password
	path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='passwordreset/password_reset_complete.html'),
		 name="password_reset_complete"),
   
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Order_Management_System_using_Django_Framework/Order-management-system/registers/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User#for profile i need User

from django.dispatch import receiver
from django.db.models.signals import post_save#user object  signal create hunxa

class Profile(models.Model):#THis is employee profile
	#in django username [assword1 and password2 are default field --but we make this model if we want to add extra field]
 
	user = models.OneToOneField(User, on_delete=models.CASCADE)#one user have one user nad pw so onetoone field
 
	fname = models.CharField(max_length=100,null=True)#null true means use value when needed
	lname = models.CharField(max_length=100,null=True)
	address = models.CharField(max_length=100, null=True)
	contact = models.CharField(max_length=100,null =True)
	email=models.EmailField(max_length=100,null=True)
	profile_img = models.ImageField(upload_to='Profile_images',default='default.png')
 
	def __str__(self):
		return self.user.username    #i use this function because i dont use null =True in user -everytime i need this
	
	
	class Meta:
		verbose_name_plural ='Profile'
		db_table = 'tbl_profile'

	def save(self,*args,**kwargs):
		super().save(*args,**kwargs)
  
  

		
		
	
	
	@receiver(post_save, sender = User)#post save paxi uend by user--for register
	def update_profile(sender,instance,created,*args,**kwargs):
		if created:
			Profile.objects.create(user=instance)
			instance.profile.save()
			
			
			
			

Order_Management_System_using_Django_Framework/Order-management-system/registers/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, AuthenticationForm

from django import forms
from django.forms import EmailField,TextInput,PasswordInput,ImageField
from .models import Profile


# from django.utils.translation import ugettext_lazy as _ #for protected-




class LoginForm(AuthenticationForm):
	# email = EmailField(label=_("Email"), required=True,help_text=_("Required.")) #Email address is protected
	pass
	
	
	#although i write email field in models this field is compulsary for extra email authentication
	#if i want to add contact i can also add contact and other that should be in model
	
	#writing meta for this is optional
	
	# class Meta:
	#     model = User
	#     fields=('username','email','password')
		
   
	

class SignupForm(UserCreationForm):
	username=forms.CharField(widget=forms.TextInput(attrs={"placeholder": " Enter Username",}))
	email=forms.EmailField(widget=forms.TextInput(attrs={"placeholder": " Enter Email",}))
	# password1=forms.CharField(widget=forms.TextInput(attrs={"placeholder": " Enter Password",'type' : 'password'}),label=_("Password"))
	# password2=forms.CharField(widget=forms.TextInput(attrs={"placeholder": " Confirm Password",'type' : 'password'}),label=_("Confirm Password"))
	

	
	class Meta:
		model = User
		

		fields = ('username','email','password1','password2',)#'__all__' also
	 
		#email fifeld is added later
		
		#help_text will remove the default text in signup page
		help_texts= {
			'username':None,
			# 'email':"Your email should contain @" if i add email and wants help_texts for that
		   #to remove help text of password and password2 go to UserCreationForm  and comment help_text in 
		}



class UpdateDefaultProfile(forms.ModelForm):
	email=forms.EmailField(widget=forms.TextInput(attrs={"placeholder": " Enter Email",}))
	class Meta:
		model = User
		fields = ('username','email',)

class UpdateCustomProfile(forms.ModelForm):
   
    	
	class Meta:
		model = Profile
		fields = ('fname','lname','address','contact','profile_img',)	
	
 

Order_Management_System_using_Django_Framework/Order-management-system/registers/views.py
from django.shortcuts import render,reverse,redirect,resolve_url

# from django.http import HttpResponseRedirect
from django.contrib.auth.views import LoginView,LogoutView
from django.conf import settings
from django.views.generic import CreateView

from .forms import SignupForm,LoginForm,UpdateDefaultProfile,UpdateCustomProfile
from django.contrib import messages
from customers.models import Customer
from orders.models import Order
from registers.models import Profile
from products.models import Product
# ,HistConf
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from .decorators import unauthenticated_user, allowed_users, admin_only
from django.http import HttpResponse, HttpResponseRedirect
import json

from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from registers.filters import CustomerFilter

# from datetime import datetime
# from django.utils import timezone
from datetime import datetime, timedelta


# from django.contrib.auth.mixins import LoginRequiredMixin

# @allowed_users(allowed_roles=['admin'])
@login_required(login_url='/user/login/')
# @admin_only
def dashboard(request):
	# customer = Customer.objects.get(pk=cid)
	customers=Customer.objects.all()
	total_customers=customers.count()
	orders=Order.objects.all()

	total_orders=orders.count()
	products = Product.objects.all()
	total_products = products.count()	
	pending=orders.filter(status='Pending').count()#filter la choose(search)  garxa and all pending lai count garxa
	delivered=orders.filter(status="Delivered").count()
 
 
	myFilter = CustomerFilter(request.GET, queryset=customers)
	customers = myFilter.qs #in jinja this customers goes

	# today_date = datetime.today()#filter every day order product for daily expenses	

	# today_customers = customers.filter(date_created__year = today_date.year,date_created__month = today_date.month,
	#                                 date_created__day = today_date.day).count()
	
	today_customers = customers.filter(date_created__gte = datetime.now() - timedelta(days=1)).count()#details of last 24 hours#b4 i also get same output using above line but now not so use this concept
	# today_order = orders.filter(created_at__year = today_date.year,created_at__month = today_date.month,created_at__day = today_date.day)
	today_order = orders.filter(created_at__gte = datetime.now() - timedelta(days=1))#A timedelta object represents a duration, the difference between two dates or times.

	order_total_price=0.00
 
	for order in today_order:
		per_total_price = float(order.product.price) * order.quantity
		
		order_total_price += per_total_price
  
	print(order_total_price)
	# customer = Customer.objects.get(pk=cid) #but i need pk = cid(update)
	# particular_customer_price=0.00
	# for order in customer.order_set.all():
	# 	per_total_price = float(order.product.price) * order.quantity
	# 	particular_customer_price += per_total_price 
	context={
			'customers':customers,'orders_total_price':order_total_price,'total_orders':total_orders,
   			'myFilter':myFilter,'today_customers':today_customers,'current_data':datetime.now(),
			'orders_pending':pending,'orders_delivered':delivered,'total_products':total_products,'total_customers':total_customers
			}
	
	return render(request,'registers/index.html',context)


# Create your views here.
def first_page(request):
	current_date = datetime.now()
	return render(request,'registers/firstpage.html',{'current_date':current_date})


@unauthenticated_user
def loginPage(request):
	form = LoginForm()
	# form = LoginForm(request.POST or None)

	if request.method == 'POST':
		username = request.POST.get('username')#grabing username from form input value
		password =request.POST.get('password')
		email =request.POST.get('email')
		user = authenticate(request,email=email, username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect('home')
		else:
			messages.error(request, 'Username OR password is incorrect')

	context = {'form':form}
	return render(request, 'registers/login.html', context)




@unauthenticated_user
def SignupView(request):

	form = SignupForm()
 
	if request.method == 'POST':
		form = SignupForm(request.POST)
		if form.is_valid():
			user = form.save()
			username = form.cleaned_data.get('username')#retrieving username from save data from form

			group = Group.objects.get(name='employee')#any time a user signup it is associated with employee group directly
			user.groups.add(group)
			print("--------------",user)

			messages.success(request, 'Account was created for ' + username)

			return redirect('register_app:login')
		

	context = {'form':form}
	return render(request, 'registers/register.html', context)


"""
class SignupView(CreateView):
	template_name = 'registers/register.html'
	form_class = SignupForm
	
	def form_valid(self,form):
		# email = form.cleaned_data.get('email') #for extra attribite
		# contact = form.cleaned_data.get('contact')
		#various sms and others
		form.save()
		# user = form.cleaned_data.get('username')
		# messages.add_message(self.request, messages.INFO, ' Account successfully register for ' +user)
		return redirect('register_app:login')
"""
  
	

class UserLogout(LogoutView):
	'''
	I use LOGOUT_REDIRECT_URL in setting.py so,when i logout then setting ma set garako url ma janxa for logout
	LOGOUT_REDIRECT_URL = '/user/login/
	'''
	# template_name = 'logout.html'
	pass





# @admin_only
# def adminProfile(request):
#     return render(request,'registers/admin_view.html')



#below package is for changing password form

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm


def UserProfile(request):
	defaultForm = UpdateDefaultProfile(instance=request.user)
	customForm = UpdateCustomProfile(instance=request.user.profile)
	PassForm = PasswordChangeForm(request.user)
	
	if request.method == 'POST' and 'profile_edit' in request.POST:#name = profile_edit in submit button
		defaultForm = UpdateDefaultProfile(request.POST,instance=request.user)
		customForm = UpdateCustomProfile(request.POST,request.FILES,instance=request.user.profile)
  
		if defaultForm.is_valid() and customForm.is_valid():
			defaultForm.save()
			customForm.save()
		
			messages.success(request,"Your record is successfully updated")
			return redirect('register_app:user_view')


	if request.method == 'POST' and 'change_pass_button' in request.POST:
		
		PassForm = PasswordChangeForm(user = request.user,data = request.POST)#i dnot see instance when changing password
  
		if PassForm.is_valid():
			PassForm.save()
			update_session_auth_hash(request, PassForm.user)  # Important!
			messages.success(request,"Your password is successfully updated")
			return redirect('register_app:user_view')
		
	return render(request,'registers/edit_user.html',{'defaultForm':defaultForm,'customForm':customForm,'PassForm':PassForm})

	

Order_Management_System_using_Django_Framework/Order-management-system/registers/templates/registers/admin_view.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Admin-Profile{% endblock %}

{% block css %}

<link rel="stylesheet" type="text/css" href="{% static 'registers/view.css' %}" />

{% endblock %}

{% block content %}

<div class="modal fade" id="adminModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title " style="margin-left: 150px;" id="exampleModalLabel">Admin Profile</h5>

          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

            <div id="box">
                <img id="profile_pic" src="{% static 'image/admin.JPG' %}"/>

                <h2>Hey, Im {{user.username}}</h2>

                <p>{{user.email}}</p>
                <p>Odisha,Puri,Konark</p>
                <p>+91 7842344652</p>

            </div>

        </div>

      </div>
    </div>
  </div>
{% endblock %}

Order_Management_System_using_Django_Framework/Order-management-system/registers/templates/registers/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link href="{% static 'vendor/css/styles.css' %}" rel="stylesheet" />
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
        crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js"
        crossorigin="anonymous"></script>

</head>

<body class="sb-nav-fixed">
    <div class="row">

            <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
                <a class="navbar-brand" href="/"><i class="fas fa-home"></i> Home</a>
                <button type="button" id="sidebarToggle" class="btn btn-warning text-black-50">
                    <i class="fas fa-align-left"></i>
                  </button>

                    <div class="col">

                        <span class=" float-right" style="color:white;"> Hello, {{request.user.username}}</span>

                    </div>

                    <div class="col">

                       <a class="btn btn-sm btn-warning float-right" data-toggle="modal" data-target="#logOutModal" style="cursor: pointer;">  <i class="fa fa-sign-in-alt"></i> LOGOUT</a>
                    </div>

            </nav>
        </div>

    </div>
    <div id="logOutModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Want to leave ?</h4>
                    <button class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    Press logout to leave !
                </div>
                <div class="modal-footer">
                    <button class="btn btn-success" data-dismiss="modal"><!--model-dismiss la same page ma lauxa-->
                        Stay Here
                    </button>
                    <a class="btn btn-danger"  href="{% url 'register_app:logout' %}">
                        Logout</a>
                </div>
            </div>
        </div>
    </div>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Functions</div>
                        <a class="nav-link" href="/dashboard">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-tachometer-alt"></i>
                            </div>
                            Dashboard
                        </a>
                        <div class="sb-sidenav-menu-heading">Interface</div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts"
                            aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-columns"></i>
                            </div>
                            Pages
                            <div class="sb-sidenav-collapse-arrow">
                                <i class="fas fa-angle-down"></i></div>
                        </a>

                        <div class="(collapse)" id="collapseLayouts" aria-labelledby="headingOne"
                            data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="{% url 'product_app:list'%}"><i class="fas fa-bars"></i><span class="ml-1">Products</span></a>
                                <a class="nav-link" href="{% url 'order_app:list'%}"><i class="fas fa-bars"></i><span class="ml-1">Orders</span></a>
                                <a class="nav-link" href="{% url 'customer_app:list'%}"><i class="fas fa-bars"></i><span class="ml-1">Customers</span></a>

                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                            aria-expanded="false" aria-controls="collapsePages">

                            <div class="sb-nav-link-icon">
                                <i class="fas fa-book-open"></i>
                            </div>
                            Authentication
                            <div class="sb-sidenav-collapse-arrow">
                                <i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="(collapse)" id="collapsePages" aria-labelledby="headingTwo"
                            data-parent="#sidenavAccordion">

                            <nav class="sb-sidenav-menu-nested nav">
                                {% if user.is_authenticated %}

                                <a class="nav-link" href="{% url 'register_app:logout'%}"><i class="fas fa-sign-out-alt"></i>Logout</a>

                                {% else %}
                                <a class="nav-link" href="{% url 'register_app:login'%}">Login</a>
                                <a class="nav-link" href="{% url 'register_app:register'%}">Register</a>
                                {% endif %}
                            </nav>
                        </div>
                    </div>

            </nav>
        </div>

        <div id="layoutSidenav_content">
            <main>

              <div class= "text-center"><strong>Last Login :</strong> {{request.user.last_login}}</div>


                <div class="card-body">
                    <h2 class="card-header">Order Management System</h2>

                </div>

                <div class="row">

                    <div class="col">
                        <div class="col-md">
                            <div class="card bg-secondary text-center text-white  mb-3" id="orders-delivered">
                                <div class="card-header">
                                    <h5 class="card-title">Today Sales</h5>
                                </div>
                                <div class="card-body">
                                    <h5 class="card-title">${{orders_total_price}}</h5>
                                </div>
                            </div>
                        </div>
                        <div class="mb-5 ml-3">
                            <a href="{% url 'order_app:list' %}" class="btn btn-warning"><i class="fas fa-eye"></i>  View Orders</a>
                        </div>

                    </div>

                    <div class="col">
                        <div class="col-md">
                            <div class="card bg-info text-center text-white  mb-3" id="orders-pending">
                                <div class="card-header">
                                    <h5 class="card-title">Today Customers</h5>
                                </div>
                                <div class="card-body">
                                    <h5 class="card-title">{{today_customers}}</h5>
                                </div>
                            </div>
                        </div>
                        <div class="mb-5 ml-3">
                            <a href="{% url 'customer_app:list'%}" class="btn btn-warning"><i class="fas fa-eye"></i>  View details</a>
                        </div>

                    </div>

                    <div class="col">
                        <div class="col-md">
                            <div class="card bg-primary text-center text-white ml-2 mb-3" id="total-orders">
                                <div class="card-header">
                                    <h5 class="card-title">Total Products</h5>
                                </div>
                                <div class="card-body">
                                    <h5 class="card-title">{{total_products}}</h5>
                                </div>
                            </div>
                        </div>
                        <div class="mb-5 ml-4">
                            <a href="{% url 'product_app:list' %}" class="btn btn-warning"><i class="fas fa-eye"></i>  View details</a>
                        </div>
                    </div>

                    <div class="col">
                        <div class="col-md">
                            <div class="card bg-success text-center text-white  mb-3" id="orders-pending">
                                <div class="card-header">
                                    <h5 class="card-title">Total Customers</h5>
                                </div>
                                <div class="card-body">
                                    <h5 class="card-title">{{total_customers}}</h5>
                                </div>
                            </div>
                        </div>
                        <div class="mb-5 ml-3">
                            <a href="{% url 'customer_app:list'%}" class="btn btn-warning"><i class="fas fa-eye"></i>  View details</a>
                        </div>

                    </div>
                </div>
                <div class="card mb-4">

                    <div class="row">
                        <div class="col">
                            <div class="card-header"><i class="fas fa-table mr-1"></i>Summary Table<hr>

                                    {% include 'registers/index_search.html' %}

                        </div>

                    </div>

                </div>
                    <div class="card-body">
                        <div class="table-responsive">

                            <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>View</th>
                                        <th>Customer</th>
                                        <th>Customer Id</th>
                                        <th>Date</th>
                                    </tr>
                                </thead>
                             {% for customer in customers %}

                             <tbody>
                                <tr>
                                    <td><a href=" {% url 'customer_app:bill' customer.id  %}"><i class="fas fa-2x fa-file-pdf"></i></a></td>
                                    <td>{{customer.name}}</td>
                                    <td>{{customer.id}}</td>

                                    <td>{{customer.date_created}}</td>
                                </tr>
                            </tbody>
                            {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                         <strong>   <div class="text-muted">Copyright &copy; Soumya Ranjan Prusty</div></strong>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
                </h3>
        </div>
        <script>

    $(document).ready(function(){
        var path = window.location.href;
        $("#layoutSidenav_nav .sb-sidenav a.nav-link").each(function() {
            if (this.href === path) {
                $(this).addClass("active");
            }
        });

    $("#sidebarToggle").on("click", function(e) {
        e.preventDefault();
        $("body").toggleClass("sb-sidenav-toggled");
    });

    })
        </script>
</body>
</html>

Order_Management_System_using_Django_Framework/Order-management-system/registers/templates/registers/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock%}

{% block content %}

<a href="/" class="btn btn-lg btn-primary mt-2"> <i class="fas fa-home"></i> Home</a>


<div style="margin-left:20%;margin-right:2%;">

  {% include 'message.html' %}
</div>
<div id="layoutAuthentication">
  <div id="layoutAuthentication_content">
    <main>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-5">
            <div class="card shadow-lg border-0 rounded-lg mt-5">


              <div class="card-header">
                <h2 class="text-center font-weight-light my-4">Login</h2>
              </div>

              <div class="card-body">

                <form method="POST" class="justify-content-center">
                  {% csrf_token %}

                  {{form|crispy}}

                  <input type="submit" name="submit" value="Login" class="btn btn-block btn-success">
                  <div class="form-check mt-2 mr-sm-2">
                    <input
                      class="form-check-input"
                      type="checkbox"
                      id="inlineFormCheck"
                    />
                    <label class="form-check-label" for="inlineFormCheck">
                      Remember me
                    </label>
                  </div><hr>

                  <div class="row">
                    <div class="col">
                      <a  class="small" href="/reset_password/">Forgot Password?</a>
                    </div>
                    <div class="col">
                    <a class="small" href="{% url 'register_app:register'%}"> Create New Account!</a>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>

</div>

<style>
  body{
		background: #a1c4fd;

	  }
</style>

{% endblock %}